"""empty message

Revision ID: fa7a264a5fb1
Revises: 1c6a8a2fe602
Create Date: 2018-08-09 10:44:10.541552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7a264a5fb1'
down_revision = '1c6a8a2fe602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###
